// <auto-generated />
using System;
using AppTurismoIndustrial.Api.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AppTurismoIndustrial.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260526000513_AddImportCandidates")]
    partial class AddImportCandidates
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AppTurismoIndustrial.Api.Features.Empresas.Empresa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Cep")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<string>("CnaePrincipal")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Cnpj")
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DescricaoCnae")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("GooglePlaceId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal>("Latitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("numeric(9,6)");

                    b.Property<decimal>("Longitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("numeric(9,6)");

                    b.Property<int>("MatrizOuFilial")
                        .HasColumnType("integer");

                    b.Property<string>("Municipio")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("NomeFantasia")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int?>("NumeroFuncionarios")
                        .HasColumnType("integer");

                    b.Property<int>("Porte")
                        .HasColumnType("integer");

                    b.Property<string>("RazaoSocial")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Setor")
                        .HasColumnType("integer");

                    b.Property<int>("SituacaoCadastral")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Telefone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("Cnpj")
                        .IsUnique()
                        .HasDatabaseName("ux_empresas_cnpj")
                        .HasFilter("\"Cnpj\" IS NOT NULL");

                    b.HasIndex("GooglePlaceId")
                        .IsUnique()
                        .HasDatabaseName("ux_empresas_google_place_id")
                        .HasFilter("\"GooglePlaceId\" IS NOT NULL");

                    b.ToTable("empresas", (string)null);
                });

            modelBuilder.Entity("AppTurismoIndustrial.Api.Features.Empresas.GoogleMapsImport.GoogleMapsImportCandidate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CepOrigem")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("EmpresaDecididoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("EmpresaId")
                        .HasColumnType("uuid");

                    b.Property<int>("EmpresaStatus")
                        .HasColumnType("integer");

                    b.Property<string>("FormattedAddress")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("GoogleMapsImportLogId")
                        .HasColumnType("uuid");

                    b.Property<string>("GooglePlaceId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal>("Latitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("numeric(9,6)");

                    b.Property<decimal>("Longitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("numeric(9,6)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("PontoDecididoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("PontoInstitucionalId")
                        .HasColumnType("uuid");

                    b.Property<int>("PontoStatus")
                        .HasColumnType("integer");

                    b.Property<string>("Telefone")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("TelefoneDecididoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TelefoneStatus")
                        .HasColumnType("integer");

                    b.Property<Guid?>("TelefoneUtilId")
                        .HasColumnType("uuid");

                    b.Property<string>("TypesJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaStatus")
                        .HasDatabaseName("ix_import_candidates_empresa_status");

                    b.HasIndex("GoogleMapsImportLogId")
                        .HasDatabaseName("ix_import_candidates_log");

                    b.HasIndex("GooglePlaceId")
                        .IsUnique()
                        .HasDatabaseName("ux_import_candidates_place_id");

                    b.HasIndex("PontoStatus")
                        .HasDatabaseName("ix_import_candidates_ponto_status");

                    b.HasIndex("TelefoneStatus")
                        .HasDatabaseName("ix_import_candidates_telefone_status");

                    b.ToTable("google_maps_import_candidates", (string)null);
                });

            modelBuilder.Entity("AppTurismoIndustrial.Api.Features.Empresas.GoogleMapsImport.GoogleMapsImportLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Cep")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EmpresasAtualizadas")
                        .HasColumnType("integer");

                    b.Property<int>("EmpresasCriadas")
                        .HasColumnType("integer");

                    b.Property<int>("EmpresasIgnoradas")
                        .HasColumnType("integer");

                    b.Property<string>("Erro")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<decimal>("LatitudeOrigem")
                        .HasColumnType("numeric");

                    b.Property<decimal>("LongitudeOrigem")
                        .HasColumnType("numeric");

                    b.Property<int>("RaioMetros")
                        .HasColumnType("integer");

                    b.Property<string>("ResponseRaw")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("google_maps_import_log");
                });

            modelBuilder.Entity("AppTurismoIndustrial.Api.Features.PontosInstitucionais.PontoInstitucional", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AtividadesDisponiveis")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<bool?>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<string>("CardFotoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ContatoEmail")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("ContatoNome")
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)");

                    b.Property<string>("ContatoTelefone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("CorMarcador")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)");

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("EquipeGestao")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("IconeMarcador")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<decimal>("Latitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("numeric(9,6)");

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<decimal>("Longitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("numeric(9,6)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)");

                    b.Property<int?>("OrdemExibicao")
                        .HasColumnType("integer");

                    b.Property<string>("ResponsavelFotoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("pontos_institucionais");
                });

            modelBuilder.Entity("AppTurismoIndustrial.Api.Features.TelefonesUteis.TelefoneUtil", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool?>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<int>("Categoria")
                        .HasColumnType("integer");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)");

                    b.Property<int?>("OrdemExibicao")
                        .HasColumnType("integer");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.HasKey("Id");

                    b.ToTable("telefones_uteis");
                });

            modelBuilder.Entity("AppTurismoIndustrial.Api.Features.Empresas.GoogleMapsImport.GoogleMapsImportCandidate", b =>
                {
                    b.HasOne("AppTurismoIndustrial.Api.Features.Empresas.GoogleMapsImport.GoogleMapsImportLog", "Log")
                        .WithMany()
                        .HasForeignKey("GoogleMapsImportLogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Log");
                });
#pragma warning restore 612, 618
        }
    }
}
